version: '3.9'
services:
  app:
    build: .
    hostname: host.docker.internal
    ports:
      - "3000:3000"
    environment:
      HOST: 0.0.0.0
      PORT: 3000
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./data:/app/data
      - ./uploads:/app/uploads
    networks:
      default:
        aliases:
          - host.docker.internal
